#!/usr/bin/env python3
"""
PITCH GENERATOR - Auto-generate investor/partner pitches
Uses ledger data + AI to create compelling narratives
"""
import json
import sys
from datetime import datetime
from pathlib import Path

# Add parent for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

def get_system_metrics():
    """Gather real metrics from the system"""
    try:
        import requests
        r = requests.get("http://localhost:3000/api/state", timeout=5)
        if r.status_code == 200:
            data = r.json().get('data', {})
            return {
                'blocks': data.get('blocks', 0),
                'users': data.get('users', 0),
                'quests_completed': data.get('quests_completed', 0),
                'at_minted': data.get('total_at', 0),
                'uptime_days': data.get('uptime_days', 0)
            }
    except:
        pass
    
    # Fallback mock data for demo
    return {
        'blocks': 150,
        'users': 25,
        'quests_completed': 47,
        'at_minted': 523.5,
        'uptime_days': 30
    }

def generate_elevator_pitch(metrics):
    """30-second elevator pitch"""
    return f"""
**The Ark: Civilization OS**

We're building an economic operating system where your time has value.

**The Problem**: Everyone's bored. Merchants need help. But traditional employment is broken—too much friction, overhead, and exploitation.

**The Solution**: The Abundance Token. Complete micro-quests, earn tokens backed by real labor. Spend them locally. No banks, no middlemen, no bullshit.

**Traction**: 
- {metrics['users']} active users
- {metrics['quests_completed']} quests completed
- {metrics['at_minted']:.1f} AT minted (labor-hours tokenized)
- {metrics['blocks']} verified ledger blocks

**Ask**: Pilot deployment with 3 local merchants. Zero cash investment—just access to your customers' boredom.

*"We don't fight the old system. We make it obsolete."*
"""

def generate_investor_deck_text(metrics):
    """Full investor deck content"""
    return f"""
# The Ark: Civilization OS
### Investor Brief | {datetime.now().strftime('%B %Y')}

---

## Executive Summary

The Ark is a **labor-backed economic protocol** that transforms idle human energy into productive action through gamified micro-quests.

**Market Opportunity**: $500B+ gig economy addressing the wrong problem. We're not competing with Uber—we're competing with Netflix for your attention.

---

## The Problem

1. **Boredom Epidemic**: 40% of adults report chronic boredom. They scroll instead of producing.
2. **Merchant Labor Shortage**: Small businesses can't afford employees for micro-tasks.
3. **Friction in Gig Work**: Too much overhead for small tasks (<1 hour).

---

## The Solution

**Quest Board**: Merchants post micro-tasks ("Sweep floor: 2 AT")  
**Completion**: Users do the task, get verified by witnesses  
**Reward**: Labor-backed tokens (AT) minted instantly  
**Spend**: Use AT at participating merchants or convert to fiat  

---

## Traction (Alpha v1.0)

| Metric | Value |
|--------|-------|
| Active Users | {metrics['users']} |
| Quests Completed | {metrics['quests_completed']} |
| AT Minted | {metrics['at_minted']:.1f} |
| Ledger Blocks | {metrics['blocks']} |
| System Uptime | {metrics['uptime_days']} days |

---

## Business Model

1. **Transaction Fee**: 2% on AT↔Fiat conversions
2. **Merchant SaaS**: $50/month for Quest Board access
3. **Hardware**: Kiosk sales (Raspberry Pi + Touch: $200/unit)
4. **Federation Licensing**: Enterprise nodes for cities/campuses

---

## Competitive Advantage

- **Not Crypto**: No speculation. 1 AT = 1 verified labor hour.
- **Not Gig Economy**: No races to the bottom. Fair rates.
- **Not a Startup**: Open source. Can't be killed by funding drought.
- **Mesh Architecture**: Dunbar-limited nodes (150 people). Anti-fragile.

---

## Team

- **Founder**: Systems architect with 140+ IQ, neurodivergent hyperfocus, and a network of engineers ready to deploy.
- **AI Collaborator**: GAIA NEXUS autonomous improvement system.
- **Advisors**: OSE community, JPL engineers, neurodivergent developer collective.

---

## Ask

**$50K Seed** for:
- 10 merchant pilots
- 100 kiosk deployments
- 6 months runway

**Alternative**: Partnership instead of investment. Provide access, not cash.

---

*"This is going to change the world. It'll be a BTC killer."* — Marcin Jakubowski, OSE Founder

---

## Contact

[Generated by Ark Pitch Generator]
"""

def generate_partner_email(merchant_name, metrics):
    """Email template for merchant partnerships"""
    return f"""
Subject: Free Labor for {merchant_name}? (Not a Scam)

Hi there,

I'm building something called The Ark—an economic system where people earn tokens by completing small tasks.

**Here's the deal for {merchant_name}:**
- You post micro-quests ("Sweep floor", "Write a review")
- People complete them and earn AT (Abundance Tokens)
- They spend those tokens at your business (or others)
- You get free labor. They get value. Everyone wins.

**Why this works:**
Everyone's bored. They're scrolling TikTok looking for something to do. Give them a quest.

**What I need from you:**
- 15 minutes to show you the app
- Permission to deploy a small kiosk (optional)
- Willingness to post 3 quests as a pilot

**What's the catch?**
No catch. I'm building a new economic system and I need real-world data. You're my beta test.

We already have {metrics['users']} users and {metrics['quests_completed']} completed quests.

Interested? Reply "quest" and I'll set up a demo.

— [Your Name]
"""

def main():
    import argparse
    parser = argparse.ArgumentParser(description='Generate pitches')
    parser.add_argument('--type', choices=['elevator', 'investor', 'email'],
                       default='elevator', help='Pitch type')
    parser.add_argument('--merchant', type=str, default='Your Business',
                       help='Merchant name for email')
    args = parser.parse_args()
    
    metrics = get_system_metrics()
    
    if args.type == 'elevator':
        print(generate_elevator_pitch(metrics))
    elif args.type == 'investor':
        print(generate_investor_deck_text(metrics))
    elif args.type == 'email':
        print(generate_partner_email(args.merchant, metrics))

if __name__ == '__main__':
    main()
